DELETE FROM stg.Product; DELETE FROM stg.Customer; DELETE FROM stg.Store;
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P001', 'Widget Model 1', 'Widgets', 'Premium', '593.51', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P002', 'Gadget Model 2', 'Gadgets', 'Basic', '71.26', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P003', 'Gadget Model 3', 'Gadgets', 'Advanced', '283.77', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P004', 'Fitting Model 4', 'Fittings', 'Standard', '239.73', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P005', 'Widget Model 5', 'Widgets', 'Standard', '676.0', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P006', 'Widget Model 6', 'Widgets', 'Premium', '625.19', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P007', 'Gadget Model 7', 'Gadgets', 'Basic', '808.35', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P008', 'Gadget Model 8', 'Gadgets', 'Advanced', '123.9', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P009', 'Fitting Model 9', 'Fittings', 'Standard', '408.63', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P010', 'Widget Model 10', 'Widgets', 'Standard', '75.33', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P011', 'Widget Model 11', 'Widgets', 'Premium', '235.84', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P012', 'Gadget Model 12', 'Gadgets', 'Basic', '479.55', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P013', 'Gadget Model 13', 'Gadgets', 'Advanced', '72.56', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P014', 'Fitting Model 14', 'Fittings', 'Standard', '219.01', '1');
INSERT INTO stg.Product (ProductId, ProductName, Category, SubCategory, UnitPrice, IsActive) VALUES ('P015', 'Widget Model 15', 'Widgets', 'Standard', '602.4', '1');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C001', 'Arjun Menon', 'arjun.menon@example.com', 'Bengaluru', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C002', 'Lata Das', 'lata.das@example.com', 'Hyderabad', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C003', 'Deepak Nair', 'deepak.nair@example.com', 'Chennai', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C004', 'Sunita Nair', 'sunita.nair@example.com', 'Hyderabad', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C005', 'Deepak Sharma', 'deepak.sharma@example.com', 'Chennai', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C006', 'Lata Das', 'lata.das@example.com', 'Hyderabad', 'India', 'SMB');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C007', 'Sneha Sharma', 'sneha.sharma@example.com', 'Pune', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C008', 'Arjun Das', 'arjun.das@example.com', 'Mumbai', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C009', 'Lata Rao', 'lata.rao@example.com', 'Hyderabad', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C010', 'Sunita Das', 'sunita.das@example.com', 'Hyderabad', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C011', 'Priya Menon', 'priya.menon@example.com', 'Chennai', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C012', 'Kavita Verma', 'kavita.verma@example.com', 'Chennai', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C013', 'Sunita Das', 'sunita.das@example.com', 'Hyderabad', 'India', 'SMB');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C014', 'Anil Rao', 'anil.rao@example.com', 'Bengaluru', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C015', 'Deepak Das', 'deepak.das@example.com', 'Mumbai', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C016', 'Kavita Kumar', 'kavita.kumar@example.com', 'Bengaluru', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C017', 'Kavita Menon', 'kavita.menon@example.com', 'Chennai', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C018', 'Sunita Nair', 'sunita.nair@example.com', 'Bengaluru', 'India', 'SMB');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C019', 'Sneha Menon', 'sneha.menon@example.com', 'Pune', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C020', 'Mohan Verma', 'mohan.verma@example.com', 'Bengaluru', 'India', 'SMB');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C021', 'Arjun Das', 'arjun.das@example.com', 'Mumbai', 'India', 'Enterprise');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C022', 'Lata Menon', 'lata.menon@example.com', 'Chennai', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C023', 'Anil Iyer', 'anil.iyer@example.com', 'Hyderabad', 'India', 'Retail');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C024', 'Priya Verma', 'priya.verma@example.com', 'Bengaluru', 'India', 'SMB');
INSERT INTO stg.Customer (CustomerId, CustomerName, Email, City, Country, Segment) VALUES ('C025', 'Deepak Sharma', 'deepak.sharma@example.com', 'Pune', 'India', 'Enterprise');
INSERT INTO stg.Store (StoreId, StoreName, Region, City) VALUES ('S01', 'Hyderabad Central', 'South', 'Hyderabad');
INSERT INTO stg.Store (StoreId, StoreName, Region, City) VALUES ('S02', 'Bengaluru Tech Park', 'South', 'Bengaluru');
INSERT INTO stg.Store (StoreId, StoreName, Region, City) VALUES ('S03', 'Chennai Marina', 'South', 'Chennai');
INSERT INTO stg.Store (StoreId, StoreName, Region, City) VALUES ('S04', 'Pune West', 'West', 'Pune');
INSERT INTO stg.Store (StoreId, StoreName, Region, City) VALUES ('S05', 'Mumbai Central', 'West', 'Mumbai');
